"""Add servings to cocktail model

Revision ID: 2863e120584b
Revises: c4dce3350de5
Create Date: 2026-03-02 18:35:08.829821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2863e120584b'
down_revision = 'c4dce3350de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.drop_column('servings')

    # ### end Alembic commands ###
