"""add subtypes to ingredients

Revision ID: 2bdb33636dc3
Revises: 761ea4953fd0
Create Date: 2026-03-31 14:00:07.219619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdb33636dc3'
down_revision = '761ea4953fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('family', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('flavour', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_ingredient_base_type'), ['base_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_base_type'))
        batch_op.drop_column('flavour')
        batch_op.drop_column('role')
        batch_op.drop_column('family')
        batch_op.drop_column('type')
        batch_op.drop_column('base_type')

    # ### end Alembic commands ###
