"""add imgage url to cocktails

Revision ID: 4ea8d370490a
Revises: 09cf65c38d65
Create Date: 2026-03-26 16:13:59.023566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea8d370490a'
down_revision = '09cf65c38d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
