"""Add quantities to cocktail model

Revision ID: 6122e233ea55
Revises: defc42deafc2
Create Date: 2026-02-25 16:48:39.422278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6122e233ea55'
down_revision = 'defc42deafc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail_ingredients', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
