"""empty message

Revision ID: 761ea4953fd0
Revises: 4ea8d370490a
Create Date: 2026-03-26 16:43:11.500549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761ea4953fd0'
down_revision = '4ea8d370490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktail', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
